### ISSUE TITLE
connection 

### ISSUE THREAD

**Issue by hamad12125** [grimlockrocks/pi-bluetooth-obd#4]
can i get help 
`Ports:
['/dev/rfcomm0']
[obd.obd] ======================= python-OBD (v0.7.1) =======================
[obd.obd] Explicit port defined
[obd.elm327] Initializing ELM327: PORT=/dev/rfcomm0 BAUD=auto PROTOCOL=auto
Traceback (most recent call last):
  File "python.py", line 11, in <module>
    connection = obd.OBD(ports[0])
  File "/home/pi/.local/lib/python2.7/site-packages/obd/obd.py", line 64, in __init__
    check_voltage, start_low_power)  # initialize by connecting and loading sensors
  File "/home/pi/.local/lib/python2.7/site-packages/obd/obd.py", line 95, in __connect
    start_low_power)
  File "/home/pi/.local/lib/python2.7/site-packages/obd/elm327.py", line 144, in __init__
    if not self.set_baudrate(baudrate):
  File "/home/pi/.local/lib/python2.7/site-packages/obd/elm327.py", line 290, in set_baudrate
    return self.auto_baudrate()
  File "/home/pi/.local/lib/python2.7/site-packages/obd/elm327.py", line 320, in auto_baudrate
    response = self.__port.read(1024)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
`

**Comment by batinh** [comment]
I have same issue. Anyone have any hint on this?
